# **NumPy** 

In [1]:
import numpy as np

## The Basics of NumPy

In [2]:
# Basic Arrays 
# 1D
a = np.array([1, 2, 5])
print(a)

[1 2 5]


In [3]:
# 2d and etc
b = np.array([[1.5, 5.0, 4.3], [2.4, 5.3, 2.2]])
print(b)

[[1.5 5.  4.3]
 [2.4 5.3 2.2]]


In [4]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# Get Shape
a.shape
b.shape

(2, 3)

In [6]:
# Get Type
b.dtype

dtype('float64')

In [7]:
a.dtype

dtype('int32')

In [8]:
# Get Size 
b.itemsize
a.itemsize

4

In [9]:
# We Can Change The Size By Using Dtype=""
# For Example:
a = np.array([1, 2, 5], dtype= 'int16')
a.itemsize

2

In [10]:
# Get Total Size
b.size * b.itemsize
# Or
b.nbytes

48

## Using NumPy In Real World

In [11]:
a = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

In [12]:
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [13]:
# Get specific element [r, c]
a[1, 3]

10

In [14]:
# Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6])

In [15]:
# Get specific column
a[:, 3]

array([ 4, 10])

In [16]:
# [start:end:step]
a[0, 1:6:2]

array([2, 4, 6])

In [17]:
# Changing
a[1, 3] = 20
print(a)

a[:, 2] = [1, 2]
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 20 11 12]]
[[ 1  2  1  4  5  6]
 [ 7  8  2 20 11 12]]


### 3D

In [18]:
b = np.array([[[1, 2], [3, 4]], [[5,6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
b[0, 1, 1]

4

In [20]:
b[0, 1:]

array([[3, 4]])

In [21]:
b[:, 0 ,:]
b[:, 1 ,:]

array([[3, 4],
       [7, 8]])

In [22]:
b[:, 1 ,:] = [[6 , 6], [1, 1]]

In [23]:
b

array([[[1, 2],
        [6, 6]],

       [[5, 6],
        [1, 1]]])

## Diffrerent Type Of Arrays

In [24]:
# All 0 Matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.zeros((2, 3, 2, 2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [26]:
# All 1
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
# Any Number
np.full((2, 2), 9)

array([[9, 9],
       [9, 9]])

In [28]:
# Full Like
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [29]:
# Random
np.random.rand(4, 2) # for int you can use randint

array([[0.73916845, 0.98269187],
       [0.57823789, 0.75160611],
       [0.84651211, 0.7329955 ],
       [0.29468028, 0.85416342]])

In [30]:
# Identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
# Repeat
arr = np.array([[1, 2, 4]])
r1 = np.repeat(arr, 4, axis=0)
print(r1)

[[1 2 4]
 [1 2 4]
 [1 2 4]
 [1 2 4]]


In [48]:
# Funny Moment
first = np.zeros((5,5))
print(first)

second = np.ones((3, 3))
print(second)

third = second[1, 1] = 9
print(second)

first[1:-1, 1:-1] = second
print(first)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 9. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 9. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## Mathematic

In [50]:
a = np.array([1, 2, 3])
print(a)
b = np.array([3, 4, 5])
print(b)

[1 2 3]
[3 4 5]


In [51]:
a + 2

array([3, 4, 5])

In [56]:
a - 2

array([-1,  0,  1])

In [57]:
a / 2

array([0.5, 1. , 1.5])

In [53]:
a * 2

array([2, 4, 6])

In [54]:
a**2

array([1, 4, 9])

In [55]:
a + b

array([4, 6, 8])

## Linear Algebra

In [62]:
a = np.ones([2, 3])
print(a)

b = np.full([3, 2], 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [68]:
# Find The Determinant
c = np.identity(3)
print(c)

print(f"Determinant: {np.linalg.det(c)}")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Determinant: 1.0


## Statistics

In [69]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [71]:
np.min(a)

1

In [72]:
np.min(a, axis=1)

array([1, 4])

In [73]:
np.max(a)

6

In [74]:
np.sum(a)

21

## Reorganizing Arrays

In [78]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [80]:
# Vertical stack
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack((v1, v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
# Horizontal stack
h1 = np.zeros((2, 4))
h2 = np.ones((2, 2))

np.hstack((h1, h2))

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])