In [2]:
import numpy as np 
import matplotlib as mp 
import sklearn as sl 
import pandas as pd

C:\Users\Parsa Barghi\AppData\Local\Temp\ipykernel_7104\3881694071.py:4: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


## preproccesing

start with numpy


In [20]:
# create array 

a  = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [21]:
# create matrix 2d
b = np.array([[1, 2], [3, 4]]) 
b

array([[1, 2],
       [3, 4]])

In [23]:
# shape
print(a.shape)
print(b.shape)

(4,)
(2, 2)


In [24]:
# reshape, make vector or 1d
c = a.reshape((4,1))
print(c.shape)
print(a.shape)

(4, 1)
(4,)


In [26]:
# make tensor or 3d
d = a.reshape((2, 2, 1))
print(d.shape)

(2, 2, 1)


In [27]:
# if you dont know about numbers of sth you can use -1
d = a.reshape((2, -1, 1))
print(d.shape)

(2, 2, 1)


In [3]:
# concatenate

a = ([1, 2, 3])
b = ([4, 5, 6])

c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5, 6])

In [4]:
# numpy have a brodcasting, you can +- 

In [4]:
# chose a special part of array 

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a.shape
b = a.reshape((9,1))
b.shape
# use slice commands
c = b[1:8:1]
c
# use bigger or smaller
d = b[b<5]
d

array([1, 2, 3, 4])

In [8]:
# plus everything in a array (jam hamashoon) we use sum
a
sum_a = np.sum(a)
sum_a
# find max in a array 
max_a = np.max(a)
max_a
# find min in a array
min_a = np.min(a)
min_a

1

In [9]:
# sort a array 
a = np.array([1, 3, 6, 8, 2, 4, 7, 88])
b = np.sort(a)
b

array([ 1,  2,  3,  4,  6,  7,  8, 88])

In [12]:
# make a random matrix
a = np.random.randint(0,100,1)
a

array([38])

In [15]:
# stack the lists 
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# vertical
c = np.vstack((a, b))
c
# horizental
c = np.hstack((a, b))
c

array([1, 2, 3, 4, 5, 6])

In [16]:
c.shape

(6,)

In [21]:
# normalize data (very important)
a
# maingin
mean_a = np.mean(a)
mean_a
# enheraf as meayar
std_a = np.std(a)
std_a
# make normalize
norm_a = (a - mean_a)/std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [22]:
np.mean(norm_a)

0.0

In [23]:
np.std(norm_a)

0.9999999999999999